workflows:
  ios-workflow:
    name: ios_workflow
    environment:
      vars:
        XCODE_WORKSPACE: "TelefonicaTest.xcworkspace"
        XCODE_SCHEME: "TelefonicaTest"
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Build
        script: |
            xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Boot device
        script: |
            xcrun simctl boot 8CEB7AD4-02CB-43C0-8C0D-7876D1655CB9
      - name: Run tests
        script: |
            xcodebuild test \
                -workspace TelefonicaTest.xcworkspace \
                -scheme TelefonicaTest \
                -sdk iphonesimulator \
                -enableCodeCoverage YES \
                -destination id=8CEB7AD4-02CB-43C0-8C0D-7876D1655CB9

